name:                twitch-analytics-haskell
version:             0.1.0.0
github:              "githubuser/twitch-analytics-haskell"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package

dependencies:
- base >= 4.7 && < 5
- aeson
- http-client
- http-client-tls
- postgresql-simple
- resource-pool
- servant
- servant-client
- text

library:
  source-dirs: src
  exposed-modules:
    - Database
    - TwitchAPI
    - TwitchParser
  ghc-options:
    - -Wall
    - -Werror

executables:
  twitch-analytics-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - twitch-analytics-haskell

tests:
  twitch-analytics-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Spec
    dependencies:
    - twitch-analytics-haskell
    - bytestring
    - test-framework
    - test-framework-hunit
    - HUnit
    - text
    - template-haskell
